server:
  port: 11002

spring:
  profiles:
    active: 
    - default

  application:
    name: MSSP-party-01
  zipkin:
    baseUrl: http://13.124.235.101:9411/
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
   
  datasource:
    url: jdbc:h2:mem:party
    driverClassName: org.h2.Driver
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

logging:
  level: 
    org.hibernate.type: trace
